# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wolf\PycharmProjects\pfc_demo\ui_src\main.ui',
# licensing of 'C:\Users\wolf\PycharmProjects\pfc_demo\ui_src\main.ui' applies.
#
# Created: Fri Jan 10 15:28:18 2020
#      by: pyside2-uic  running on PySide2 5.11.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 634)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.project_id = QtWidgets.QLineEdit(Form)
        self.project_id.setObjectName("project_id")
        self.horizontalLayout_4.addWidget(self.project_id)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.forward_number = QtWidgets.QLineEdit(Form)
        self.forward_number.setObjectName("forward_number")
        self.horizontalLayout.addWidget(self.forward_number)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.forward_times = QtWidgets.QLineEdit(Form)
        self.forward_times.setObjectName("forward_times")
        self.horizontalLayout.addWidget(self.forward_times)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), Form.make_sample)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), Form.clear)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL("clicked()"), Form.parallel_bond)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL("clicked()"), Form.ucs)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL("clicked()"), Form.plot_stress_strain)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL("clicked()"), Form.cycle)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL("clicked()"), Form.go_to_start)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), Form.duplicate)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL("clicked()"), Form.plot_temp)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "项目ID：", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Form", "清空工作区", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "生成试样", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("Form", "回到试样起点", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("Form", "生成parallel bond连接", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("Form", "单轴压缩", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("Form", "应力位移曲线", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("Form", "复制当前项目", None, -1))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("Form", "绘制临时图像", None, -1))
        self.forward_number.setText(QtWidgets.QApplication.translate("Form", "1000", None, -1))
        self.forward_number.setPlaceholderText(QtWidgets.QApplication.translate("Form", "前进的帧数", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "帧", None, -1))
        self.forward_times.setText(QtWidgets.QApplication.translate("Form", "1", None, -1))
        self.forward_times.setPlaceholderText(QtWidgets.QApplication.translate("Form", "前进的次数", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "次", None, -1))
        self.pushButton_9.setText(QtWidgets.QApplication.translate("Form", "前进", None, -1))

