# Generated by Django 3.0.1 on 2019-12-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名')),
                ('ball_count', models.IntegerField(verbose_name='颗粒数')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField(verbose_name='总循环次数')),
                ('strain', models.FloatField(verbose_name='总应变')),
                ('stress', models.FloatField(verbose_name='总应力')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Project', verbose_name='项目')),
            ],
        ),
    ]
