# Generated by Django 3.0.1 on 2019-12-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_remove_statistic_sav_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ball_porosity',
            field=models.FloatField(default=0.1, verbose_name='孔隙度'),
        ),
        migrations.AddField(
            model_name='project',
            name='ball_radius_max',
            field=models.FloatField(default=3, verbose_name='最大直径，单位mm'),
        ),
        migrations.AddField(
            model_name='project',
            name='ball_radius_min',
            field=models.FloatField(default=4, verbose_name='最小直径，单位mm'),
        ),
        migrations.AddField(
            model_name='project',
            name='bottom_velocity',
            field=models.FloatField(default=0.1, verbose_name='下墙上移速度，恒正，单位m/s'),
        ),
        migrations.AddField(
            model_name='project',
            name='cycle_step',
            field=models.IntegerField(default=100, verbose_name='加载时的步长'),
        ),
        migrations.AddField(
            model_name='project',
            name='damp_when_loading',
            field=models.FloatField(default=0.1, verbose_name='加载时的能量耗散率'),
        ),
        migrations.AddField(
            model_name='project',
            name='domain_extend',
            field=models.FloatField(default=2, verbose_name='计算区域扩展，单位mm'),
        ),
        migrations.AddField(
            model_name='project',
            name='panel_extend',
            field=models.FloatField(default=2, verbose_name='荷载板扩展长度，单位mm'),
        ),
        migrations.AddField(
            model_name='project',
            name='random_seed',
            field=models.IntegerField(default=10001, verbose_name='随机种子'),
        ),
        migrations.AddField(
            model_name='project',
            name='specimen_height',
            field=models.FloatField(default=150, verbose_name='试样高，单位mm'),
        ),
        migrations.AddField(
            model_name='project',
            name='specimen_width',
            field=models.FloatField(default=75, verbose_name='试样宽，单位mm'),
        ),
        migrations.AddField(
            model_name='project',
            name='top_velocity',
            field=models.FloatField(default=0.1, verbose_name='上墙下移速度，恒正，单位m/s'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ball_count',
            field=models.IntegerField(default=0, verbose_name='颗粒数，只读'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='无名称', max_length=100, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='cycle',
            field=models.IntegerField(default=0, verbose_name='总循环次数'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statistic.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='strain',
            field=models.FloatField(default=0, verbose_name='总应变'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='stress',
            field=models.FloatField(default=0, verbose_name='总应力'),
        ),
    ]
