# Generated by Django 3.0.1 on 2019-12-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_auto_20191223_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ball_radius_max',
            field=models.FloatField(default=4, verbose_name='最大直径，单位mm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ball_radius_min',
            field=models.FloatField(default=3, verbose_name='最小直径，单位mm'),
        ),
    ]
