# Generated by Django 3.0.1 on 2019-12-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_auto_20191223_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='max_cycle',
        ),
    ]
